### ISSUE TITLE
Serve multiple .qgs file from single server

### ISSUE THREAD

**Issue by Deba088** [qgis/qgis-docker#116]
I am trying to create a qgis server which can serve multiple .qgs file.
Currently, I can provide QGIS_PROJECT_FILE for a single .qgs project while running the QGIS server using docker-compose. Is there any way to serve multiple .qgs project from a directory in the server?
![Capture](https://github.com/user-attachments/assets/0b1899b0-c962-4762-878d-54ed0a05609b)

**Comment by JakobMiksch** [comment]
`QGIS_PROJECT_FILE` only defines the default project to use, see [docs](https://docs.qgis.org/3.34/en/docs/server_manual/config.html#environment-variables)

To make queries to other QGIS projects you must use the `map=/path/to/your/qgis_project` query parameter. 

However, depending on your setup you should have a rewrite of the query, so that users do not need to specify that path (also the should not be allowed to do that for security reasons). Rewriting the query is independent on this docker image. Here an example how this can be done for QGIS projects located in Postgres: https://github.com/siticom/docker-qgis-server-postgres/blob/main/postgres-access.conf This, however, uses another docker image.
